In [1]:
from sklearn.preprocessing import OneHotEncoder
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

In [2]:
# D07 - Adult
df_d07 = pd.read_csv("raw/Adult_dataset.csv")
df_d07.head()

,age,workclass,fnlwgt,education,education_num,marital_status,occupation,relationship,race,sex,capital_gain,capital_loss,hours_per_week,native_country,income,dataset_split
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K,train
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K,train
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K,train
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K,train
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K,train

---

#### **01 ) - Tratamento dos dados**

- 

---

In [3]:
try:
    _mudar_prefixo_coluna # type: ignore
except NameError:
    _mudar_prefixo_coluna = True

    df_d07_clean = df_d07.copy()
    df_d07_clean = df_d07_clean.drop(columns=['dataset_split'])
    df_d07_clean = df_d07_clean.rename(columns={'fnlwgt' : 'final_weight'})
    df_d07_clean.columns = [f"{idx}_{col}" for idx, col in enumerate(df_d07_clean.columns, start=1)]

df_d07_clean.head(10)

,1_age,2_workclass,3_final_weight,4_education,5_education_num,6_marital_status,7_occupation,8_relationship,9_race,10_sex,11_capital_gain,12_capital_loss,13_hours_per_week,14_native_country,15_income
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K
5,37,Private,284582,Masters,14,Married-civ-spouse,Exec-managerial,Wife,White,Female,0,0,40,United-States,<=50K
6,49,Private,160187,9th,5,Married-spouse-absent,Other-service,Not-in-family,Black,Female,0,0,16,Jamaica,<=50K
7,52,Self-emp-not-inc,209642,HS-grad,9,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,45,United-States,>50K
8,31,Private,45781,Masters,14,Never-married,Prof-specialty,Not-in-family,White,Female,14084,0,50,United-States,>50K
9,42,Private,159449,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,5178,0,40,United-States,>50K

In [4]:
df_d07_status = pd.read_csv("raw/D07_status.csv")
df_d07_status['column'] = df_d07_clean.columns.tolist()
df_d07_status.to_csv("raw/D07_status.csv", index=False)
df_d07_status.head(15)

,column,variable_type,variable_subtype,description,classification,transformation,status
0,1_age,quantitative,continuous,The age of the individual in years.,DEMOGRAPHIC,NaN,NaN
1,2_workclass,qualitative,nominal,The employment sector or status of the individ...,SOCIOECONOMIC,NaN,NaN
2,3_final_weight,quantitative,continuous,Final weight; a demographic weighting variable...,ERROR,NaN,NaN
3,4_education,qualitative,ordinal,The highest categorical level of education com...,SOCIOECONOMIC,NaN,NaN
4,5_education_num,quantitative,continuous,"The highest level of education completed, repr...",SOCIOECONOMIC,NaN,NaN
5,6_marital_status,qualitative,nominal,The current marital situation of the individua...,DEMOGRAPHIC,NaN,NaN
6,7_occupation,qualitative,nominal,"The specific type of work, profession, or trad...",SOCIOECONOMIC,NaN,NaN
7,8_relationship,qualitative,nominal,The individual's familial relationship to the ...,DEMOGRAPHIC,NaN,NaN
8,9_race,qualitative,nominal,The reported race or ethnic categorization of ...,DEMOGRAPHIC,NaN,NaN
9,10_sex,qualitative,nominal,The biological sex of the individual (Female o...,DEMOGRAPHIC,NaN,NaN
10,11_capital_gain,quantitative,continuous,Financial income generated from investment sou...,SOCIOECONOMIC,NaN,NaN
11,12_capital_loss,quantitative,continuous,Financial losses incurred from investment sour...,SOCIOECONOMIC,NaN,NaN
12,13_hours_per_week,quantitative,continuous,The typical number of hours the individual wor...,SOCIOECONOMIC,NaN,NaN
13,14_native_country,qualitative,nominal,The individual's primary country of origin or ...,ALTERNATIVE,NaN,NaN
14,15_income,quantitative,discrete,The target variable for classification; indica...,SOCIOECONOMIC,NaN,NaN

---

#### **02 ) - Análise da correlação Numérico / Numérico**

- 

---

In [5]:
df_d07_num = df_d07_status[(df_d07_status['variable_type'] == 'quantitative') & (df_d07_status['variable_subtype'] == 'continuous')][['column', 'variable_type','variable_subtype']].reset_index(drop=True)
df_d07_num

              column variable_type variable_subtype
0              1_age  quantitative       continuous
1     3_final_weight  quantitative       continuous
2    5_education_num  quantitative       continuous
3    11_capital_gain  quantitative       continuous
4    12_capital_loss  quantitative       continuous
5  13_hours_per_week  quantitative       continuous

In [6]:
df_d07_num_pearson = df_d07_clean[df_d07_num['column'].values.tolist()].corr(method='pearson')
df_d07_num_pearson

,1_age,3_final_weight,5_education_num,11_capital_gain,12_capital_loss,13_hours_per_week
1_age,1.000000,-0.076628,0.030940,0.077229,0.056944,0.071558
3_final_weight,-0.076628,1.000000,-0.038761,-0.003706,-0.004366,-0.013519
5_education_num,0.030940,-0.038761,1.000000,0.125146,0.080972,0.143689
11_capital_gain,0.077229,-0.003706,0.125146,1.000000,-0.031441,0.082157
12_capital_loss,0.056944,-0.004366,0.080972,-0.031441,1.000000,0.054467
13_hours_per_week,0.071558,-0.013519,0.143689,0.082157,0.054467,1.000000

In [7]:
top_10_d07_num_pearson = (
    df_d07_num_pearson.unstack().reset_index(name='Valor').set_axis(['Coluna', 'Linha', 'Valor'], axis=1).drop_duplicates(subset=['Valor']).query('Valor != 1').nlargest(10, 'Valor')
)

top_10_d07_num_pearson.index = range(1, 11)
top_10_d07_num_pearson

             Coluna              Linha     Valor
1   5_education_num  13_hours_per_week  0.143689
2   5_education_num    11_capital_gain  0.125146
3   11_capital_gain  13_hours_per_week  0.082157
4   5_education_num    12_capital_loss  0.080972
5             1_age    11_capital_gain  0.077229
6             1_age  13_hours_per_week  0.071558
7             1_age    12_capital_loss  0.056944
8   12_capital_loss  13_hours_per_week  0.054467
9             1_age    5_education_num  0.030940
10   3_final_weight    11_capital_gain -0.003706

In [8]:
df_d07_num_spearman = df_d07_clean[df_d07_num['column'].values.tolist()].corr(method='spearman')
df_d07_num_spearman

,1_age,3_final_weight,5_education_num,11_capital_gain,12_capital_loss,13_hours_per_week
1_age,1.000000,-0.077504,0.063212,0.124436,0.057584,0.146604
3_final_weight,-0.077504,1.000000,-0.029643,-0.008755,-0.000944,-0.016334
5_education_num,0.063212,-0.029643,1.000000,0.118871,0.077017,0.164437
11_capital_gain,0.124436,-0.008755,0.118871,1.000000,-0.066328,0.091914
12_capital_loss,0.057584,-0.000944,0.077017,-0.066328,1.000000,0.060063
13_hours_per_week,0.146604,-0.016334,0.164437,0.091914,0.060063,1.000000

In [9]:
top_10_d07_num_spearman = (
    df_d07_num_spearman.unstack().reset_index(name='Valor').set_axis(['Coluna', 'Linha', 'Valor'], axis=1).drop_duplicates(subset=['Valor']).query('Valor != 1').nlargest(10, 'Valor')
)

top_10_d07_num_spearman.index = range(1, 11)
top_10_d07_num_spearman

             Coluna              Linha     Valor
1   5_education_num  13_hours_per_week  0.164437
2             1_age  13_hours_per_week  0.146604
3             1_age    11_capital_gain  0.124436
4   5_education_num    11_capital_gain  0.118871
5   11_capital_gain  13_hours_per_week  0.091914
6   5_education_num    12_capital_loss  0.077017
7             1_age    5_education_num  0.063212
8   12_capital_loss  13_hours_per_week  0.060063
9             1_age    12_capital_loss  0.057584
10   3_final_weight    12_capital_loss -0.000944

In [10]:
df_d07_num_kendall = df_d07_clean[df_d07_num['column'].values.tolist()].corr(method='kendall')
df_d07_num_kendall

,1_age,3_final_weight,5_education_num,11_capital_gain,12_capital_loss,13_hours_per_week
1_age,1.000000,-0.052383,0.050856,0.100677,0.047058,0.111001
3_final_weight,-0.052383,1.000000,-0.021378,-0.007001,-0.000771,-0.011818
5_education_num,0.050856,-0.021378,1.000000,0.103358,0.067488,0.129756
11_capital_gain,0.100677,-0.007001,0.103358,1.000000,-0.064311,0.079971
12_capital_loss,0.047058,-0.000771,0.067488,-0.064311,1.000000,0.052643
13_hours_per_week,0.111001,-0.011818,0.129756,0.079971,0.052643,1.000000

In [11]:
top_10_d07_num_kendall = (
    df_d07_num_kendall.unstack().reset_index(name='Valor').set_axis(['Coluna', 'Linha', 'Valor'], axis=1).drop_duplicates(subset=['Valor']).query('Valor != 1').nlargest(10, 'Valor')
)

top_10_d07_num_kendall.index = range(1, 11)
top_10_d07_num_kendall

             Coluna              Linha     Valor
1   5_education_num  13_hours_per_week  0.129756
2             1_age  13_hours_per_week  0.111001
3   5_education_num    11_capital_gain  0.103358
4             1_age    11_capital_gain  0.100677
5   11_capital_gain  13_hours_per_week  0.079971
6   5_education_num    12_capital_loss  0.067488
7   12_capital_loss  13_hours_per_week  0.052643
8             1_age    5_education_num  0.050856
9             1_age    12_capital_loss  0.047058
10   3_final_weight    12_capital_loss -0.000771

In [ ]:
def get_num_info():
    print("Pearson:")
    print(df_d07_num_pearson)
    print("Spearman:")
    print(df_d07_num_spearman)
    print("Kendall:")
    print(df_d07_num_kendall)
    
# get_num_info()

---

#### **03 ) - Análise da associação Categórico / Categórico**

- 

---