In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

---

#### **01 ) - Importando os dados**

- 

---

In [2]:
df_d07_v1 = pd.read_csv("Input/D07_V1.csv")
df_d07_v1.head()

,1_age,2_workclass,3_final_weight,4_education,5_education_num,6_marital_status,7_occupation,8_relationship,9_race,10_sex,11_capital_gain,12_capital_loss,13_hours_per_week,14_native_country,15_income
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,0
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,0
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,0
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,0
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,0

In [3]:
df_d07_status = pd.read_csv("Input/D07_status.csv")
df_d07_status.head()

,column,variable_type,variable_subtype,description,classification,transformation,status
0,1_age,quantitative,continuous,The age of the individual in years.,DEMOGRAPHIC,NaN,NaN
1,2_workclass,qualitative,nominal,The employment sector or status of the individ...,SOCIOECONOMIC,NaN,NaN
2,3_final_weight,quantitative,continuous,Final weight; a demographic weighting variable...,ERROR,NaN,NaN
3,4_education,qualitative,ordinal,The highest categorical level of education com...,SOCIOECONOMIC,NaN,NaN
4,5_education_num,quantitative,continuous,"The highest level of education completed, repr...",SOCIOECONOMIC,NaN,NaN

---

#### **02 ) - Tratamento dos dados**

- 

---

In [4]:
# Lista de todas as variáveis quantitativas contínuas.
list_quant_con = df_d07_status[(df_d07_status['variable_type'] == 'quantitative') & (df_d07_status['variable_subtype'] == 'continuous')]['column'].to_list()

In [7]:
df_d07_status.columns

Index(['column', 'variable_type', 'variable_subtype', 'description',
       'classification', 'transformation', 'status'],
      dtype='str')

In [10]:
list_quali_nom = df_d07_status[(df_d07_status['variable_type'] == 'qualitative') & (df_d07_status['variable_subtype'] == 'nominal')]['column'].to_list()
list_quali_nom

['2_workclass',
 '6_marital_status',
 '7_occupation',
 '8_relationship',
 '9_race',
 '10_sex',
 '14_native_country']