In [1]:
import pandas as pd

In [2]:
# D02 - Default of Credit Card Clients
df_d02 = pd.read_csv("raw/DefaultData.csv")
df_d02.head()

,ID,LIMIT_BAL,SEX,EDUCATION,MARRIAGE,AGE,PAY_0,PAY_2,PAY_3,PAY_4,...,BILL_AMT4,BILL_AMT5,BILL_AMT6,PAY_AMT1,PAY_AMT2,PAY_AMT3,PAY_AMT4,PAY_AMT5,PAY_AMT6,default payment next month
0,1,20000,2,2,1,24,2,2,-1,-1,...,0,0,0,0,689,0,0,0,0,1
1,2,120000,2,2,2,26,-1,2,0,0,...,3272,3455,3261,0,1000,1000,1000,0,2000,1
2,3,90000,2,2,2,34,0,0,0,0,...,14331,14948,15549,1518,1500,1000,1000,1000,5000,0
3,4,50000,2,2,1,37,0,0,0,0,...,28314,28959,29547,2000,2019,1200,1100,1069,1000,0
4,5,50000,1,2,1,57,-1,0,-1,0,...,20940,19146,19131,2000,36681,10000,9000,689,679,0

---

#### **01 ) - Verificação dos dados**

- 

---

In [3]:
float(df_d02.isna().sum().sum() / len(df_d02) * 100)

0.0

In [4]:
bool(df_d02.duplicated().any())

False

---

#### **02 ) - Tratamento dos dados**

- 

---

In [5]:
df_d02_clean = df_d02.copy()

#### 2.1 - *Dropando colunas*

In [6]:

# Dropando a coluna ID uma vez que a mesma representa apenas uma chave primária do dataset
df_d02_clean = df_d02_clean.drop(columns=['ID'])

#### 2.2 - *Renomeando colunas*

In [7]:

# Renomeando a coluna alvo para TARGET
df_d02_clean = df_d02_clean.rename(columns={"default payment next month":'TARGET'})
# Aplicando a contagem padrão nas colunas
df_d02_clean.columns = [f"{idx}_{col}" for idx, col in enumerate(df_d02_clean.columns, start=1)]

#### 2.3 - *Tratamento para valores ausentes*

In [8]:
# O dataset D02 não possui valores ausentes

#### 2.4 - *Tratamento para valores duplicados*

In [9]:
# O dataset D02 não possui valores duplicados

#### 2.5 - *Salvando o resultado*

In [10]:
df_d02_clean.to_csv("Input/D02_Clean.csv", index=False)
df_d02_clean.head()

,1_LIMIT_BAL,2_SEX,3_EDUCATION,4_MARRIAGE,5_AGE,6_PAY_0,7_PAY_2,8_PAY_3,9_PAY_4,10_PAY_5,...,15_BILL_AMT4,16_BILL_AMT5,17_BILL_AMT6,18_PAY_AMT1,19_PAY_AMT2,20_PAY_AMT3,21_PAY_AMT4,22_PAY_AMT5,23_PAY_AMT6,24_TARGET
0,20000,2,2,1,24,2,2,-1,-1,-2,...,0,0,0,0,689,0,0,0,0,1
1,120000,2,2,2,26,-1,2,0,0,0,...,3272,3455,3261,0,1000,1000,1000,0,2000,1
2,90000,2,2,2,34,0,0,0,0,0,...,14331,14948,15549,1518,1500,1000,1000,1000,5000,0
3,50000,2,2,1,37,0,0,0,0,0,...,28314,28959,29547,2000,2019,1200,1100,1069,1000,0
4,50000,1,2,1,57,-1,0,-1,0,0,...,20940,19146,19131,2000,36681,10000,9000,689,679,0

---

#### **03 ) - Status CSV**

- 

---

In [16]:
df_d02_status = pd.read_csv("Input/D02_Status.csv")
df_d02_status['column'] = df_d02_clean.columns.tolist()
df_d02_status.to_csv("Input/D02_Status.csv", index=False)
df_d02_status

,column,variable_type,variable_subtype,description,classification,transformation,status
0,1_LIMIT_BAL,quantitative,continuous,NaN,NaN,NaN,NaN
1,2_SEX,qualitative,nominal,NaN,NaN,NaN,NaN
2,3_EDUCATION,qualitative,ordinal,NaN,NaN,NaN,NaN
3,4_MARRIAGE,qualitative,nominal,NaN,NaN,NaN,NaN
4,5_AGE,quantitative,continuous,NaN,NaN,NaN,NaN
5,6_PAY_0,qualitative,ordinal,NaN,NaN,NaN,NaN
6,7_PAY_2,qualitative,ordinal,NaN,NaN,NaN,NaN
7,8_PAY_3,qualitative,ordinal,NaN,NaN,NaN,NaN
8,9_PAY_4,qualitative,ordinal,NaN,NaN,NaN,NaN
9,10_PAY_5,qualitative,ordinal,NaN,NaN,NaN,NaN
10,11_PAY_6,qualitative,ordinal,NaN,NaN,NaN,NaN
11,12_BILL_AMT1,quantitative,continuous,NaN,NaN,NaN,NaN
12,13_BILL_AMT2,quantitative,continuous,NaN,NaN,NaN,NaN
13,14_BILL_AMT3,quantitative,continuous,NaN,NaN,NaN,NaN
14,15_BILL_AMT4,quantitative,continuous,NaN,NaN,NaN,NaN
15,16_BILL_AMT5,quantitative,continuous,NaN,NaN,NaN,NaN
16,17_BILL_AMT6,quantitative,continuous,NaN,NaN,NaN,NaN
17,18_PAY_AMT1,quantitative,continuous,NaN,NaN,NaN,NaN
18,19_PAY_AMT2,quantitative,continuous,NaN,NaN,NaN,NaN
19,20_PAY_AMT3,quantitative,continuous,NaN,NaN,NaN,NaN
20,21_PAY_AMT4,quantitative,continuous,NaN,NaN,NaN,NaN
21,22_PAY_AMT5,quantitative,continuous,NaN,NaN,NaN,NaN
22,23_PAY_AMT6,quantitative,continuous,NaN,NaN,NaN,NaN
23,24_TARGET,qualitative,nominal,NaN,NaN,NaN,NaN